name: Docker Image CI

env:
  DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ env.DOCKER_PASSWORD }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USERNAME/actions-test
    - name: Push image
      run: docker push $DOCKER_USERNAME/actions-test
